import { NextResponse } from 'next/server';
import { requireStaff } from '@/lib/auth';

export const runtime = 'nodejs';

export async function POST(req: Request) {
  const { denied, profile, supabase } = await requireStaff();
  if (denied) {
    return NextResponse.json({ error: 'Not authorized' }, { status: 403 });
  }

  let body: any;
  try { body = await req.json(); }
  catch { return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 }); }

  const { header, lines, addonIds } = body || {};
  if (!header || !Array.isArray(lines) || lines.length === 0) {
    return NextResponse.json({ error: 'Missing header or lines' }, { status: 400 });
  }
  if (!header.client_name) {
    return NextResponse.json({ error: 'client_name required' }, { status: 400 });
  }

  // 1. Insert quote header (quote_number auto-generated by trigger)
  const { data: quote, error: qErr } = await supabase
    .from('quotes')
    .insert({ ...header, owner_id: profile.id })
    .select('id, quote_number, client_token')
    .single();
  if (qErr || !quote) {
    return NextResponse.json({ error: qErr?.message || 'Quote insert failed' }, { status: 500 });
  }

  // 2. Insert lines
  const lineRows = lines.map((l: any) => ({
    quote_id: quote.id,
    sort_order: l.sort_order ?? 0,
    talent_type: l.talent_type,
    player_id: l.player_id ?? null,
    creator_id: l.creator_id ?? null,
    talent_name: l.talent_name,
    platform: l.platform,
    base_rate: l.base_rate ?? 0,
    qty: l.qty ?? 1,
    final_unit: l.final_unit ?? 0,
    final_amount: l.final_amount ?? 0,
  }));
  const { error: lErr } = await supabase.from('quote_lines').insert(lineRows);
  if (lErr) {
    // rollback header
    await supabase.from('quotes').delete().eq('id', quote.id);
    return NextResponse.json({ error: `Lines insert failed: ${lErr.message}` }, { status: 500 });
  }

  // 3. Insert add-on toggles
  if (Array.isArray(addonIds) && addonIds.length > 0) {
    const { data: addonRows } = await supabase
      .from('addons')
      .select('id, uplift_pct')
      .in('id', addonIds);
    const upserts = (addonRows || []).map(a => ({
      quote_id: quote.id,
      addon_id: a.id,
      uplift_pct: a.uplift_pct,
    }));
    if (upserts.length > 0) {
      await supabase.from('quote_addons').insert(upserts);
    }
  }

  // 4. Audit log
  await supabase.from('audit_log').insert({
    actor_id: profile.id,
    actor_email: profile.email,
    action: 'quote.create',
    entity_type: 'quote',
    entity_id: quote.id,
    diff: { quote_number: quote.quote_number, status: header.status, total: header.total },
  });

  return NextResponse.json({
    id: quote.id,
    quote_number: quote.quote_number,
    client_token: quote.client_token,
  });
}
